/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    private HashTable<String, Integer> test = new HashTable<>();
    private HashTable<String, String> test1 = new HashTable<>();
    @Test
    public void addTest(){
        test.add("ahmad1",1);
        test.add("ahmad2",2);
        test.add("ahmad3",3);
        test.add("ahmad4",4);
    }

    @Test
    public void addAssertTest(){
        test.add("ahmad5",5);
        assertEquals(test.get("ahmad5"), 5);
    }

    @Test
    public void nullTest(){
        assertNull(test.get("ahmad"));
    }

    @Test
    public void containTest(){
        test.add("ahmad1",1);
        test.add("ahmad2",2);

        assertTrue(test.contain("ahmad1"));
    }

    @Test
    public void uncontainedTest(){
        test.add("ahmad1",1);
        test.add("ahmad2",2);

        assertFalse(test.contain("ahmad"));
    }

    @Test
    public void sizeTest(){
        test.add("ahmad1",1);
        test.add("ahmad2",2);

        assertEquals(2,test.getSize());
    }
}
