/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sort;

import java.lang.reflect.Array;
import java.util.Arrays;

public class Library {
    public static void main(String[] args) {
    int[] arr={8,4,23,42,16,15};
    Sort sort =new Sort();
        System.out.println(Arrays.toString( sort.insertionSort(arr)));

    }
}
