/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class Library {
    public static void main(String[] args) {
        HashTable<String, String> first = new HashTable<>();
        first.add("e","emam");
        first.add("a","ali");
        first.add("m","malik");
        first.add("l","mona");
        first.add("s","mona");
        first.add("d","mona");
        System.out.println(first.contain("k"));
        System.out.println(first.getSize());
    }
}
