/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackqueue;

public class App {

    public static <T> void main(String[] args) {
        Stack stack1=new Stack();
        stack1.push(10);
        stack1.push(5);
        stack1.push(7);
        stack1.push(6);

        T returnedValue= (T) stack1.pop();
        System.out.println(returnedValue);
        System.out.println(stack1.toString());


        Queue queue1=new Queue();
        queue1.enqueue(2);
        queue1.enqueue(3);
        queue1.enqueue(4);
        queue1.enqueue(5);
        T returnedValueQueue=(T) queue1.dequeue();
        System.out.println(returnedValueQueue);
        System.out.println(queue1.toString());
    }
}
