/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class Library {
    public static void main(String[] args) {
        Graph graph = new Graph();
        graph.addVetrex("Bob");
        graph.addVetrex("Mary");
        graph.addVetrex("Alice");
        graph.addVetrex("Carl");
        graph.addEdge("Bob","Alice");
        graph.addEdge("Bob","Mary");
        graph.addEdge("Alice","Carl");
        System.out.println(graph.printGraph());
        System.out.println(graph.size());
//        System.out.println("/////////////////////////////////////////////////////////////");
////        graph.removeEdge("Bob","Alice");
//        graph.removeVertex("Bob");
//        System.out.println(graph.printGraph());
//        System.out.println(graph.size());
        System.out.println("/////////////////////////////////////////////////////////////");
        System.out.println(graph.dft(graph, "Alice"));
        System.out.println("/////////////////////////////////////////////////////////////");
        System.out.println(graph.bft(graph, "Alice"));
    }
}
