/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void testEmptyLinkedList(){
            LinkedList<Integer>testList=new LinkedList<Integer>();
            String expectedValue="NULL";
            assertEquals(expectedValue,testList.toString());
    }
    @Test void testInsertLinkedList(){
        LinkedList<Integer>testList=new LinkedList<Integer>();
        testList.insert(2);
        String expectedValue="{ 2 } -> NULL";
        assertEquals(expectedValue,testList.toString());
    }
    @Test void testHeadLinkedList(){
        LinkedList<Integer>testList=new LinkedList<Integer>();
        testList.insert(2);
        Integer expectedValue=2;
        assertEquals(expectedValue,testList.head.value);
    }
    @Test void testInsertMultibleLinkedList(){
        LinkedList<Integer>testList=new LinkedList<Integer>();
        testList.insert(2);
        testList.insert(3);
        testList.insert(4);
        testList.insert(5);
        testList.insert(6);

        String expectedValue="{ 6 } -> { 5 } -> { 4 } -> { 3 } -> { 2 } -> NULL";
        assertEquals(expectedValue,testList.toString());
    }
    @Test void testTrueLinkedList(){
        LinkedList<Integer>testList=new LinkedList<Integer>();
        testList.insert(2);
        testList.insert(3);
        testList.insert(4);
        testList.insert(5);
        testList.insert(6);

        boolean expectedValue=true;
        assertEquals(expectedValue,testList.includes(5));
    }
    @Test void testFalseLinkedList(){
        LinkedList<Integer>testList=new LinkedList<Integer>();
        testList.insert(2);
        testList.insert(3);
        testList.insert(4);
        testList.insert(5);
        testList.insert(6);

        boolean expectedValue=false;
        assertEquals(expectedValue,testList.includes(1));
    }
    @Test void testInsertCollectionLinkedList(){
        LinkedList<Integer>testList=new LinkedList<Integer>();
        testList.insert(2);
        testList.insert(3);
        testList.insert(4);
        testList.insert(5);
        testList.insert(6);

        String expectedValue="{ 6 } -> { 5 } -> { 4 } -> { 3 } -> { 2 } -> NULL";
        assertEquals(expectedValue,testList.toString());
    }
}
